# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Docker
  displayName: Build & Push Docker image to AWS ECR
  jobs:
  - job: Build_and_Push
    displayName: Build & Push Docker image
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: CmdLine@2
      inputs:
        script: 'dir'
      
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: 'app/Dockerfile'
        buildContext: 'app/'
        repository: guestbooknode

    - task: ECRPushImage@1
      inputs:
          awsCredentials: 'AWS-Cloudbrick'
          regionName: 'us-east-2'
          imageSource: 'imagename'
          sourceImageName: 'guestbooknode'
          repositoryName: 'guestBookNode'
