

trigger:
- main

pool:
  name: Default

stages:

      

- stage: EKS

  displayName: 'Terraform Apply'
  jobs:
  - job: TerraformApply
    displayName: 'Terraform Apply'
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'

    - script: |
        terraform --version
        terraform init
        terraform plan -out=tfplan -var 'AWS_ACCESS_KEY_ID=$(aws-access-key)' -var 'AWS_SECRET_ACCESS_KEY=$(aws-secret-key)'
        terraform apply -auto-approve tfplan
      displayName: 'Terraform Init and Apply'
      workingDirectory: infra

