

trigger:
- main

pool:
  name: Default

stages:

      

- stage: EKS

  displayName: 'Terraform Apply'
  jobs:
  - job: TerraformApply
    displayName: 'Terraform Apply'
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'

    - script: |
        terraform --version
        echo "no" | terraform init
        terraform plan -out tfplan
        terraform apply -auto-approve tfplan
      displayName: 'Terraform Init and Apply'
      workingDirectory: infra

