

trigger:
- main

pool:
  name: Default

stages:
- stage: Docker
  displayName: Build & Push Docker image to AWS ECR
  jobs:
  - job: Build_and_Push
    displayName: Build & Push Docker image
    steps:
      
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: 'app/Dockerfile'
        buildContext: 'app/'
        repository: guestbooknode
        tags: latest
    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'AWS-Cloudbrick'
        regionName: 'us-east-2'
        imageSource: 'imagename'
        sourceImageName: 'guestbooknode'
        repositoryName: 'guestbooknode'
        pushTag: latest
      
  - job: DeployImages
    displayName: 'Deploy Crudnode Environment'
    steps:
    - script: |
        aws eks update-kubeconfig --region us-east-1 --name wiz-demo
        kubectl apply -f crudnode-server-deployment.yml
        kubectl apply -f crudnode-server-service.yml
      displayName: 'Deploy Node Image'
      workingDirectory: app