

trigger:
- main

pool:
  name: Default

stages:
- stage: Docker
  displayName: Build & Push Docker image to AWS ECR
  jobs:
  - job: Build_and_Push
    displayName: Build & Push Docker image
    steps:
      
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: 'app/Dockerfile'
        buildContext: 'app/'
        repository: guestbooknode
        tags: latest
    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'AWS-Cloudbrick'
        regionName: 'us-east-2'
        imageSource: 'imagename'
        sourceImageName: 'guestbooknode'
        repositoryName: 'guestbooknode'
        pushTag: latest
      

- stage: EKS

  displayName: 'Terraform Apply'
  jobs:
  - job: TerraformApply
    displayName: 'Terraform Apply'
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'
    
    - script: |
        echo "Initializing Terraform..."
        echo "no" | terraform init
      displayName: 'Terraform Init'
      workingDirectory: infra

    - script: |
        echo "Executing Terraform Plan..."
        terraform plan -out=tfplan -var 'AWS_ACCESS_KEY_ID=$(aws-access-key)' -var 'AWS_SECRET_ACCESS_KEY=$(aws-secret-key)' -detailed-exitcode || echo "##vso[task.setvariable variable=plan_exit_code;]$?"
      displayName: 'Terraform Plan'
      continueOnError: true # This allows the pipeline to continue even if this step "fails"
      workingDirectory: infra

    - script: |
        if [ $(plan_exit_code) -eq 2 ]
         then
         echo "Applying Terraform Plan..."
         terraform apply "tfplan"
        elif [ $(plan_exit_code) -eq 0 ]
         then
          echo "No changes detected in Terraform Plan."
         else
          echo "Terraform Plan failed."
          exit 1 # Exit the pipeline as failed if Terraform plan execution was unsuccessful
        fi
      displayName: 'Conditional Terraform Apply'