

trigger:
- main

pool:
  name: Default

stages:
- stage: Docker
  displayName: Deploy Application to EKS
  jobs:
  - job: Build_and_Push
    displayName: Build & Push & Deploy to EKS
    steps:
    
    - script: |
        echo "Installing Checkov"
        pip install checkov
      displayName: 'Install Checkov'

    - script: |
        echo "Running Checkov scan"
        checkov -d . --soft-fail
      displayName: 'Run Checkov Scan'
      
    - task: Docker@2
      displayName: Build Node Image
      inputs:
        command: build
        dockerfile: 'app/node-app/Dockerfile'
        buildContext: 'app/node-app'
        repository: guestbooknode
        tags: latest
    - task: ECRPushImage@1
      displayName: Push Node Image
      inputs:
        awsCredentials: 'AWS-ErickrazrPersonal'
        regionName: 'us-east-1'
        imageSource: 'imagename'
        sourceImageName: 'guestbooknode'
        repositoryName: 'guestbooknode'
        pushTag: latest

    - task: Docker@2
      displayName: Build Spring4shell Image
      inputs:
        command: build
        dockerfile: 'app/s4shell-app/Dockerfile'
        buildContext: 'app/s4shell-app/'
        repository: s4shell
        tags: latest
    - task: ECRPushImage@1
      displayName: Push Spring4Shell Image
      inputs:
        awsCredentials: 'AWS-ErickrazrPersonal'
        regionName: 'us-east-1'
        imageSource: 'imagename'
        sourceImageName: 's4shell'
        repositoryName: 's4shell'
        pushTag: latest
      
    - script: |
        kubectl apply -f k8s/apps-namespace.yaml
        kubectl apply -f k8s/apps-server-deployment.yml
        kubectl apply -f k8s/apps-server-service.yml
      displayName: 'Deploy Applications'
      workingDirectory: app