

trigger:
- main

pool:
  name: Default

stages:
- stage: Docker
  displayName: Deploy Application to EKS
  jobs:
  - job: Build_and_Push
    displayName: Build & Push & Deploy to EKS
    steps:
    
    - script: |
        echo "Installing Checkov"
        pip install checkov
      displayName: 'Install Checkov'

    - script: |
        echo "Running Checkov scan"
        checkov -d .
      displayName: 'Run Checkov Scan'
      
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: 'app/Dockerfile'
        buildContext: 'app/'
        repository: guestbooknode
        tags: latest
    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'AWS-ErickrazrPersonal'
        regionName: 'us-east-1'
        imageSource: 'imagename'
        sourceImageName: 'guestbooknode'
        repositoryName: 'guestbooknode'
        pushTag: latest
      
    - script: |
        kubectl apply -f k8s/crudnode-namespace.yaml
        kubectl apply -f k8s/crudnode-server-deployment.yml
        kubectl apply -f k8s/crudnode-server-service.yml
      displayName: 'Deploy Node Image'
      workingDirectory: app