apiVersion: apps/v1
kind: Deployment
metadata:
  name: crudnode-server-deployment
  namespace: crudnode-ns
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: crudnode-server
    spec:
      containers:
        - name: crudnode-server
          image: 373329633988.dkr.ecr.us-east-1.amazonaws.com/guestbooknode:latest
          securityContext:
            privileged: true
          ports:
            - containerPort: 3000
              name: nodejs-port
  selector:
    matchLabels:
      app: crudnode-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s4shell-server-deployment
  namespace: s4shell-ns
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: s4shell-server
    spec:
      containers:
        - name: s4shell-server
          image: 373329633988.dkr.ecr.us-east-1.amazonaws.com/s4shell:latest
          securityContext:
            privileged: true
          ports:
            - containerPort: 8080
              name: s4shell-port
  selector:
    matchLabels:
      app: s4shell-server
