apiVersion: v1
kind: Service
metadata:
  name: crudnode-server-service
  namespace: crudnode-ns
spec:
  type: LoadBalancer
  selector:
    app: crudnode-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  name: crudnode-server-service
  namespace: crudnode-ns
---
apiVersion: v1
kind: Service
metadata:
  name: s4shell-server-service
  namespace: s4shell-ns
spec:
  type: LoadBalancer
  selector:
    app: s4shell-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8888
  name: s4shell-server-service
  namespace: s4shell-ns