apiVersion: apps/v1
kind: Deployment
metadata:
  name: crudnode-server-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: crudnode-server
    spec:
      volumes:
      - name: sec-ctx-vol
        hostPath:
          path: /etc
      containers:
        - name: crudnode-server
          image: 222668120177.dkr.ecr.us-east-2.amazonaws.com/guestbooknode:latest
          volumeMounts:
          - name: sec-ctx-vol
            mountPath: /data
          securityContext:
            privileged: true
          ports:
            - containerPort: 3000
              name: nodejs-port
  selector:
    matchLabels:
      app: crudnode-server
